/**:
  ros__parameters:
    buffers/image_qos_depth: 2
    buffers/imu_qos_depth: 512
    buffers/lidar_qos_depth: 4
    buffers/max_image_frames: 8
    buffers/max_imu_samples: 2000
    buffers/max_lidar_frames: 30
    common/img_en: 0
    common/img_topic: /camera/camera/color/image_raw
    common/imu_topic: /livox/imu
    common/lid_msg_type: pointcloud2
    common/lid_topic: /livox/lidar_local
    common/lidar_en: 1
    extrin_calib/Pcl: !!python/tuple
    - -0.0198
    - -0.0744
    - -0.00023434
    extrin_calib/Rcl: !!python/tuple
    - -0.0117
    - -0.9999
    - 0.0115
    - 0.508
    - -0.0158
    - -0.8612
    - 0.8613
    - -0.0042
    - 0.5081
    extrin_calib/extrinsic_R: !!python/tuple
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    extrin_calib/extrinsic_T: !!python/tuple
    - 0.04165
    - 0.02326
    - -0.0284
    frames/base: base_link
    frames/base_pitch_correction_deg: -30.0
    frames/base_roll_correction_deg: 0.0
    frames/base_to_lidar_quaternion: !!python/tuple
    - 0.0
    - 0.25881904510252074
    - 0.0
    - 0.9659258262890683
    frames/base_to_lidar_translation: !!python/tuple
    - 0.0
    - 0.0
    - 0.9
    frames/base_yaw_correction_deg: 0.0
    frames/odom: odom
    imu/acc_cov: 0.5
    imu/gyr_cov: 0.3
    imu/imu_en: true
    imu/imu_int_frame: 30
    imu/init_pitch_deg: 30.0
    imu/init_roll_deg: 0.0
    imu/init_yaw_deg: 0.0
    laserMapping/cam_cx: 651.6027
    laserMapping/cam_cy: 371.2037
    laserMapping/cam_d0: -0.0549
    laserMapping/cam_d1: 0.0746
    laserMapping/cam_d2: 0.0
    laserMapping/cam_d3: 0.0
    laserMapping/cam_fx: 655.8494
    laserMapping/cam_fy: 656.0487
    laserMapping/cam_height: 720
    laserMapping/cam_model: Pinhole
    laserMapping/cam_width: 1280
    laserMapping/scale: 1.0
    lio/beam_err: 0.05
    lio/dept_err: 0.02
    lio/max_layer: 2
    lio/min_eigen_value: 0.0025
    lio/voxel_size: 0.5
    preprocess/blind: 0.8
    preprocess/filter_size_surf: 0.1
    preprocess/lidar_type: 1
    preprocess/point_filter_num: 1
    preprocess/scan_line: 6
    use_sim_time: false
